export const Disciplinasprivadas = [

    { id: 1, nombre: "Ballet Clásico" },
    { id: 2, nombre: "Ballet Neoclásico" },
    { id: 3, nombre: "Ballet Contemporáneo" },
    { id: 4, nombre: "Danza Moderna" },
    { id: 5, nombre: "Danza Jazz" },
    { id: 6, nombre: "Danza Contemporánea" },
    { id: 7, nombre: "Danza Folklórica Argentina" },
    { id: 8, nombre: "Danza Étnica o Danza Tradicional (Folklore Mundial)" },
    { id: 9, nombre: "Danza Urbana" },
    { id: 10, nombre: "Hip-hop" },
    { id: 11, nombre: "Breaking" },
    { id: 12, nombre: "Locking" },
    { id: 13, nombre: "Popping" },
    { id: 14, nombre: "Krumping" },
    { id: 15, nombre: "Waacking" },
    { id: 16, nombre: "Salsa" },
    { id: 17, nombre: "Bachata" },
    { id: 18, nombre: "Tango" },
    { id: 19, nombre: "Swing" },
    { id: 20, nombre: "Rumba" },
    { id: 21, nombre: "Cha-cha-cha" },
    { id: 22, nombre: "Merengue" },
    { id: 23, nombre: "Foxtrot" },
    { id: 24, nombre: "Vals / Waltz" },
    { id: 25, nombre: "Danzas Españolas " },
    { id: 26, nombre: "Danzas de la India" },
    { id: 27, nombre: "Bhangra (Punjab, India y Pakistán)" },
    { id: 28, nombre: "Capoeira (Brasil)" },
    { id: 29, nombre: "Irish Step Dance (Irlanda)" },
    { id: 30, nombre: "Cossack Dance (Europa del Este)" },
    { id: 31, nombre: "Danzas Africanas" },
    { id: 32, nombre: "Danza Acrobática" },
    { id: 33, nombre: "Danzas Árabes" },
    { id: 34, nombre: "Otras" },
]