const Municipios = [
    { id: 1, nombre: "POSADAS" },
    { id: 2, nombre: "FACHINAL" },
    { id: 3, nombre: "OBERÁ" },
    { id: 4, nombre: "APOSTOLES" },
    { id: 5, nombre: "JARDÍN AMÉRICA" },
    { id: 6, nombre: "MONTECARLO" },
    { id: 7, nombre: "25 DE MAYO" },
    { id: 8, nombre: "9 DE JULIO" },
    { id: 9, nombre: "ALBA POSSE" },
    { id: 10, nombre: "ALMAFUERTE" },
    { id: 11, nombre: "ARISTOBULO DEL VALLE" },
    { id: 12, nombre: "ARROYO DEL MEDIO" },
    { id: 13, nombre: "AZARA" },
    { id: 14, nombre: "BERNARDO DE IRIGOYEN" },
    { id: 15, nombre: "BONPLAND" },
    { id: 16, nombre: "CAA YARÍ" },
    { id: 17, nombre: "CAMPO GRANDE" },
    { id: 18, nombre: "CAMPO RAMÓN" },
    { id: 19, nombre: "CAMPO VIERA" },
    { id: 20, nombre: "CANDELARIA" },
    { id: 21, nombre: "CAPIOVÍ" },
    { id: 22, nombre: "CARAGUATAY" },
    { id: 23, nombre: "CERRO AZUL" },
    { id: 24, nombre: "CERRO CORÁ" },
    { id: 25, nombre: "COMANDANTE ANDRESITO" },
    { id: 26, nombre: "COLONIA ALBERDI" },
    { id: 27, nombre: "COLONIA AURORA" },
    { id: 28, nombre: "COLONIA DELICIA" },
    { id: 29, nombre: "COLONIA POLANA" },
    { id: 30, nombre: "COLONIA VICTORIA" },
    { id: 31, nombre: "COLONIA WANDA" },
    { id: 32, nombre: "CONCEPCIÓN DE LA SIERRA" },
    { id: 33, nombre: "CORPUS" },
    { id: 34, nombre: "DOS ARROYOS" },
    { id: 35, nombre: "DOS DE MAYO" },
    { id: 36, nombre: "EL ALCAZAR" },
    { id: 37, nombre: "EL SOBERBIO" },
    { id: 38, nombre: "ELDORADO" },
    { id: 39, nombre: "FLORENTINO AMEGHINO" },
    { id: 40, nombre: "GARUHAPÉ" },
    { id: 41, nombre: "GARUPÁ" },
    { id: 42, nombre: "GENERAL ALVEAR" },
    { id: 43, nombre: "GENERAL URQUIZA" },
    { id: 44, nombre: "GOBERNADOR LÓPEZ" },
    { id: 45, nombre: "GOBERNADOR ROCA" },
    { id: 46, nombre: "GUARANÍ" },
    { id: 47, nombre: "HIPÓLITO IRIGOYEN" },
    { id: 48, nombre: "PUERTO IGUAZÚ" },
    { id: 49, nombre: "ITACARUARÉ" },
    { id: 50, nombre: "LEANDRO N. ALEM" },
    { id: 51, nombre: "PUERTO LIBERTAD" },
    { id: 52, nombre: "LORETO" },
    { id: 53, nombre: "LOS HELECHOS" },
    { id: 54, nombre: "MÁRTIRES" },
    { id: 55, nombre: "MOJÓN GRANDE" },
    { id: 56, nombre: "OLEGARIO VICTOR ANDRADE" },
    { id: 57, nombre: "PANAMBÍ" },
    { id: 58, nombre: "PROFUNDIDAD" },
    { id: 59, nombre: "PUERTO ESPERANZA" },
    { id: 60, nombre: "PUERTO LEONI" },
    { id: 61, nombre: "PUERTO PIRAY" },
    { id: 62, nombre: "PUERTO RICO" },
    { id: 63, nombre: "RUIZ DE MONTOYA" },
    { id: 64, nombre: "SAN ANTONIO" },
    { id: 65, nombre: "SAN JAVIER" },
    { id: 66, nombre: "SAN JOSÉ" },
    { id: 67, nombre: "SAN MARTÍN" },
    { id: 68, nombre: "SAN PEDRO" },
    { id: 69, nombre: "SAN VICENTE" },
    { id: 70, nombre: "SANTA ANA" },
    { id: 71, nombre: "SANTA MARÍA" },
    { id: 72, nombre: "SANTIAGO DE LINIERS" },
    { id: 73, nombre: "SANTO PIPÓ" },
    { id: 74, nombre: "TRES CAPONES" },
    { id: 75, nombre: "SALTO ENCANTADO" },
    { id: 76, nombre: "POZO AZUL" }
  ]
  